### ISSUE TITLE
ECIP 1054 - Atlantis Hardfork Tracker

### ISSUE THREAD

**Issue by soc1c** [eth-classic/go-ethereum#18]
I don't want to mess with #1, but I would suggest creating tracking issues for each milestone of Ethereum Classic, here: [ECIP 1054 - Atlantis](https://github.com/ethereumclassic/ECIPs/blob/master/ECIPs/ECIP-1054.md)

### Review Spec

- [x] Please take time to review [ECIP 1054 - Atlantis](https://github.com/ethereumclassic/ECIPs/blob/master/ECIPs/ECIP-1054.md) (it's in LAST CALL state)

### Implement Upgrades

- [x] Add `Atlantis` transition/config that activates at
   - [ ] `1_039_000` on Kotti Classic PoA-testnet (early August 2019)
   - [x] `4_723_000` on Morden Classic PoW-testnet (early August 2019)
   - [x] `8_750_000` on Ethereum Classic PoW-mainnet (mid-September 2019)
- [x] Implement the proposals
  - [x] [EIP 100](https://eips.ethereum.org/EIPS/eip-100) (Change difficulty adjustment to target mean block time including uncles) #36 
  - [x] [EIP 140](https://eips.ethereum.org/EIPS/eip-140) (`REVERT` instruction in the Ethereum Virtual Machine) #34 
  - [x] [EIP 161](https://eips.ethereum.org/EIPS/eip-161) (State-trie clearing) #28 
  - [x] [EIP 170](https://eips.ethereum.org/EIPS/eip-170) (Contract-code size limit) #23 
  - [x] [EIP 196](https://eips.ethereum.org/EIPS/eip-196) (Precompiled contracts for addition and scalar multiplication on the elliptic curve `alt_bn128`) #24 
  - [x] [EIP 197](https://eips.ethereum.org/EIPS/eip-197) (Precompiled contracts for optimal ate pairing check on the elliptic curve `alt_bn128`) #24 
  - [x] [EIP 198](https://eips.ethereum.org/EIPS/eip-198) (Precompiled contract for BIGINT modular exponentiation) #24 
  - [x] [EIP 211](https://eips.ethereum.org/EIPS/eip-211) (New opcodes `RETURNDATASIZE` and `RETURNDATACOPY`) #37 
  - [x] [EIP 214](https://eips.ethereum.org/EIPS/eip-214) (New opcode `STATICCALL`) #40 
  - [x] [EIP 658](https://eips.ethereum.org/EIPS/eip-658) (Embedding transaction status code in receipts) #62
