### ISSUE TITLE
ECIP-1056 - Agharta Hardfork Tracker

### ISSUE THREAD

**Issue by soc1c** [eth-classic/go-ethereum#20]
ref https://github.com/etclabscore/ECIPs/pull/13 (and #1)

After Atlantis #18 comes Agharta.

### Review Spec

- [ ] Please take time to review [ECIP 1056 - Agharta](https://github.com/etclabscore/ECIPs/blob/f54b24ed42900d86e1786eeadf37826c39629d56/ECIPs/ECIP-1056.md) (it's in DRAFT state)

### Implement Upgrades

- [ ] Add `Agharta` transition/config that activates at
  - [ ] `1_500_000` on Kotti Classic PoA-testnet (early November 2019)
  - [ ] `5_200_000` on Morden Classic PoW-testnet (early November 2019)
  - [ ] `9_200_000` on Ethereum Classic PoW-mainnet (early December 2019)
- [ ] Implement the proposals
  - [ ] [EIP 145](https://eips.ethereum.org/EIPS/eip-145) (Bitwise shifting instructions)
  - [ ] [EIP 1014](https://eips.ethereum.org/EIPS/eip-1014) (Skinny `CREATE2` opcode)
  - [ ] [EIP 1052](https://eips.ethereum.org/EIPS/eip-1052) (`EXTCODEHASH` opcode)

Edit Daniel-1: Add checkboxes to tasks
