### ISSUE TITLE
[WIP] Atlantis Testnet & Mainnet Strategy

### ISSUE THREAD

**Issue by GregTheGreek** [eth-classic/go-ethereum#44]
NOTE: this is preparation for our geth client. References to Parity are meant to be local changes for testing, not to Parity's actual repository.

In preparation for Atlantis(#18) we will need to ensure we have properly set our config(#39) for both Morden and Mainnet. Tentatively, it looks like we will be triggering the Mainnet launch much earlier (early-mid July) and the testnet this week. I have outlined a proposed go to launch strategy and more than open to suggestions:

- [x] 1. Update Configurations (Parity and Geth)
    - [x] 1. Update mainnet Atlantis block number to 8,500,000
    - [x] 2. Update Morden Atlantis block number to 4,729,274
- [x] 2. Network Simulations
    - [x] 1. Test locally Geth<>Geth
    - [x] 2. Test with a cloud instance of Geth<>Geth
    - [x] 3. Test locally with a Geth<>Parity
    - [x] 4. Test with a cloud instance of Geth (cloud) <> Parity (local)
- [x] 3. Testnet
    - [x] 1. Spin up ~3 Geth nodes in the cloud (Digital Ocean) for a persistent network
    - [x] 2. Ensure that the Atlantis has triggered
    - [x] 3. IFF all is well, tear down network, connect to the existing Morden network
    - [x] 4. IFF all is well, get boot node and distribute to other miners (Morden Network)
    - [x] 5. ~IFF all is well for X days, proceed with mainnet~
- [ ] 4. Mainnet 
    - IFF all goes smooth in the testnet, proceed with mainnet.
    - [x] 1. Get participating mainnet nodes in a group(?)
    - [ ] 2. Give them constant updates on testnet progress
    - [ ] 3. Have them update X days prior to launch(?)
    - [x] 4. IFF no bugs arise during the testnet proceed to mainnet

Edit: re-ordered a few items and added the note.
